info:
  description: MSM API
  version: 0.1.0-dev
  contact:
    email: holger.graef@gmail.com
  license:
    name: GPL v3
    url: https://github.com/HolgerGraef/MSM/blob/master/LICENSE.md
  title: MSM API
tags:
- name: samples
  description: Endpoints related to samples
- name: shares
  description: Endpoints related to shares
- name: actions
  description: Endpoints related to actions
paths:
  /api/sample:
    put:
      operationId: createSample
      tags:
      - samples
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NewSampleFormContent'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewSampleResponse'
          description: Sample created
  /api/sample/{id}:
    delete:
      operationId: deleteSample
      tags:
      - samples
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Sample deleted
  /api/sample/{id}/togglearchived:
    post:
      operationId: toggleArchived
      tags:
      - samples
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToggleArchivedResponse'
          description: isarchived-flag toggled
  /api/sample/{id}/togglecollaborative:
    post:
      operationId: toggleCollaborative
      tags:
      - samples
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToggleCollaborativeResponse'
          description: iscollaborative-flag toggled
  /api/sample/{id}/changeparent/{parentid}:
    post:
      operationId: changeParent
      tags:
      - samples
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      - in: path
        name: parentid
        schema:
          type: integer
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: parent changed
  /api/share:
    put:
      operationId: createShare
      tags:
      - shares
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateShareContent'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Share created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateShareError'
          description: Failed to create share
  /api/share/{id}:
    delete:
      operationId: deleteShare
      tags:
      - shares
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Share deleted
        '205':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Share deleted, sample no longer accessible for current user
  /api/action/{sampleid}:
    put:
      operationId: createAction
      tags:
      - actions
      parameters:
      - in: path
        name: sampleid
        schema:
          type: integer
        required: true
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NewActionFormContent'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Action created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateActionError'
          description: Failed to create action
  /api/action/{id}:
    delete:
      operationId: deleteAction
      tags:
      - actions
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Action deleted
  /api/action/swaporder:
    post:
      operationId: swapActionOrder
      tags:
      - actions
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SwapActionOrderContent'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Action order swapped
  /api/action/markasnews:
    post:
      operationId: markActionAsNews
      tags:
      - actions
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MarkActionAsNewsContent'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Action marked as news
  /api/action/unmarkasnews:
    post:
      operationId: unmarkActionAsNews
      tags:
      - actions
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UnmarkActionAsNewsContent'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Action unmarked as news
  /api/get/{target}/{field}/{id}:
    get:
      operationId: getField
      tags:
      - fields
      parameters:
      - in: path
        name: field
        schema:
          type: string
        required: true
      - in: path
        name: target
        schema:
          type: string
          enum:
          - sample
          - action
          - share
          - smbresource
          - user
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Value'
          description: Field value fetched successfully
  /api/set/{target}/{field}/{id}:
    post:
      operationId: setField
      tags:
      - fields
      parameters:
      - in: path
        name: field
        schema:
          type: string
        required: true
      - in: path
        name: target
        schema:
          type: string
          enum:
          - sample
          - action
          - share
          - smbresource
          - user
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Value'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Field value updated successfully
openapi: 3.0.2
components:
  schemas:
    NewSampleFormContent:
      type: object
      properties:
        newsampleparent:
          type: string
        newsamplename:
          type: string
        newsampledescription:
          type: string
        newsampleparentid:
          type: integer
        csrf_token:
          type: string
    NewSampleResponse:
      type: object
      properties:
        sampleid:
          type: integer
    Empty:
      type: object
      properties: {}
    ToggleArchivedResponse:
      type: object
      properties:
        isarchived:
          type: boolean
    ToggleCollaborativeResponse:
      type: object
      properties:
        iscollaborative:
          type: boolean
    CreateShareContent:
      type: object
      properties:
        sampleid:
          type: integer
        userid:
          type: integer
        username:
          type: string
    CreateShareError:
      type: object
      properties: {}
    NewActionFormContent:
      type: object
      properties:
        timestamp:
          type: string
          format: date
        description:
          type: string
        csrf_token:
          type: string
    CreateActionError:
      type: object
      properties:
        resubmit:
          type: boolean
    SwapActionOrderContent:
      type: object
      properties:
        actionid:
          type: integer
        swapid:
          type: integer
    MarkActionAsNewsContent:
      type: object
      properties:
        expires:
          type: string
          format: date
        actionid:
          type: integer
        title:
          type: string
        csrf_token:
          type: string
    UnmarkActionAsNewsContent:
      type: object
      properties:
        actionid:
          type: integer
    Value:
      type: object
      properties:
        value:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
