info:
  description: MSM API
  version: 0.1.0-dev
  contact:
    email: holger.graef@gmail.com
  license:
    name: GPL v3
    url: https://github.com/HolgerGraef/MSM/blob/master/LICENSE.md
  title: MSM API
tags:
- name: MSM
  description: Endpoints related to MSM
paths:
  /api/action/{id}:
    delete:
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
          description: Action deleted
openapi: 3.0.2
components:
  schemas:
    Empty:
      type: object
      properties: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
