languageCode:           "en"
title:                  "Racine"
baseURL:                "https://hgrf.github.io/racine"

relativeURLs:           true
canonifyURLs:           true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY
      - RACINE_VERSION

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

module:
  mounts:
    - source:           dist
      target:           static/docs/5.2/dist
    - source:           assets
      target:           assets
    - source:           content
      target:           content
    - source:           data
      target:           data
    - source:           layouts
      target:           layouts
    - source:           static
      target:           static
    - source:           static/docs/5.2/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           static/docs/5.2/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  subtitle:             "A collaborative lab book in your web browser"
  description:          "Racine is a Flask-based web app that can run in the local network. Features include file import from Samba servers, sharing samples while protecting individual users' notes, LaTeX typesetting and many more..."
  authors:              "Holger Graef"

  docs_version:         "5.2"
  github_org:           "https://github.com/hgrf"
  repo:                 "https://github.com/hgrf/racine"
  linkedin:             "https://www.linkedin.com/in/holgergraef"

  download:
    source:             "https://github.com/hgrf/racine/archive/refs/heads/master.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    css_hash:         "sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
    css_rtl:          "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css"
    css_rtl_hash:     "sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU"
    js:               "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
    js_hash:          "sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
    js_bundle:        "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    popper_hash:      "sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"

  anchors:
    min: 2
    max: 5

  testimonials:
    - name:           "Dr. Rebeca Ribeiro-Palau"
      img:            "IMGP8279.JPG"
      role:           "CNRS Researcher, Center for Nanoscience and Nanotechnology, Palaiseau, France"
      text:           "Racine is a great lab tool! We use it as a log book for samples, equipment and data treatment, and to keep everybody updated. Everything in our lab is always on Racine!"
    - name:           "Prof. Dr. Erwann Bocquillon"
      img:            "EB-FDP3_v3.jpeg"
      role:           "University Professor, ML4Q, University of Cologne, Germany"
      text:           "User friendly and easily administrable, simple and powerful, Racine is perfectly suited to our needs. A great tool for our group!"
    - name:           "Dr. Emmanuel Baudin"
      img:            "emmanuel_baudin.png"
      role:           "Researcher, École Normale Supérieure, Paris, France"
      text:           "In our lab we have a large collection of samples which are moved between several institutes. Working in large collaborations, it is essential to be able to retrieve data and information on samples and measurements done long ago and by different people. This task would be very hard without Racine."
    - name:           "Mario Di Luca"
      role:           "PhD candidate, Laboratory of Quantum Physics, Topology and Correlations, EPFL, Lausanne, Switzerland"
      img:            "IMG_20230201_133822_575.jpg"
      text:           "In our group we use Racine to keep track of everything we do, from fabrication to measurements. Easy to use and accessible from everywhere, Racine is the perfect lab notebook! "
    - name:           "Dr. Everton Arrighi"
      img:            "Everton.jpeg"
      role:           "Research Engineer, QCMX lab, École Polytechnique, Palaiseau, France"
      text:           "Racine is like a swiss army knife in a laboratory organization. From keeping standard recipes in a easily accessible place, up to taking real time notes of every step of sample fabrication, manipulation and measurements. Thanks to its user-friendly interface, all the important details can be recorded with just a few keystrokes.  And with its intelligent structure, it can keep track of a large number of samples in an organized way. An indispensable tool for any laboratory!"
    - name:           "Holger Graef"
      img:            "IMG_7415_portrait.jpg"
      role:           "Developer of Racine"
      text:           "When I realized that keeping track of multiple samples over numerous fabrication and characterization steps inside and outside of the cleanroom using paper notebooks was rather tedious, I started developing Racine and have used it myself for over four years."
