languageCode:           "en"
title:                  "Mercury Sample Manager"
baseURL:                "https://holgergraef.github.io/MSM"

relativeURLs:           true
canonifyURLs:           true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

module:
  mounts:
    - source:           dist
      target:           static/docs/5.2/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/5.2/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/5.2/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  subtitle:             "A collaborative lab book in your web browser"
  description:          "MSM is a Flask-based web app that can run in the local network. Features include file import from Samba servers, sharing samples while protecting individual users' notes, LaTeX typesetting and many more..."
  authors:              "Holger Graef"

  current_version:      "0.1.0-dev"
  docs_version:         "5.2"
  github_org:           "https://github.com/HolgerGraef"
  repo:                 "https://github.com/HolgerGraef/MSM"
  linkedin:             "https://www.linkedin.com/in/holgergraef"

  download:
    source:             "https://github.com/HolgerGraef/MSM/archive/refs/heads/master.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    css_hash:         "sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
    css_rtl:          "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css"
    css_rtl_hash:     "sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU"
    js:               "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
    js_hash:          "sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
    js_bundle:        "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    popper_hash:      "sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"

  anchors:
    min: 2
    max: 5

  testimonials:
    - name:           "Dr. Rebeca Ribeiro-Palau"
      img:            "IMGP8279.JPG"
      role:           "CNRS Researcher, Center for Nanoscience and Nanotechnology, Palaiseau, France"
      text:           "MSM is a great lab tool! We use it as a log book for samples, equipment and data treatment, and to keep everybody updated. Everything in our lab is always on Mercury!"
    - name:           "Prof. Dr. Erwann Bocquillon"
      img:            "EB-FDP3_v3.jpeg"
      role:           "University Professor, ML4Q, University of Cologne, Germany"
      text:           "User friendly and easily administrable, simple and powerful, the Mercury Sample Manager is perfectly suited to our needs. A great tool for our group!"
    - name:           "Mario Di Luca"
      role:           "PhD candidate, Laboratory of Quantum Physics, Topology and Correlations, EPFL, Lausanne, Switzerland"
      img:            "IMG_20230201_133822_575.jpg"
      text:           "In our group we use Mercury Sample Manager to keep track of everything we do, from fabrication to measurements. Easy to use and accessible from everywhere, MSM is the perfect lab notebook! "
    - name:           "Holger Graef"
      img:            "IMG_7415_portrait.jpg"
      role:           "Developer of MSM"
      text:           "When I realized that keeping track of multiple samples over numerous fabrication and characterization steps inside and outside of the cleanroom using paper notebooks was rather tedious, I started developing MSM and have used it myself for over four years."
