version: "3.9"
services:
  web:
    image: ghcr.io/hgrf/racine
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: racine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - uploads:/app/uploads
      - database:/app/database
      - ./ssl:/etc/nginx/ssl
  web-dev:
    container_name: racine-dev
    image: racine-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: racine-base
    ports:
      - "8080:80"
    volumes:
      - ..:/app
volumes:
  uploads:
  database:
