version: "3.9"
services:
  web:
    image: ghcr.io/hgrf/racine
    container_name: racine-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/app/data
      - database:/app/database
      - uploads:/app/uploads
      - ./ssl:/etc/nginx/ssl
  redis:
    container_name: racine-redis
    image: redis:7.0.11
  celery-worker:
    depends_on:
      - redis
    container_name: racine-celery-worker
    image: ghcr.io/hgrf/racine
    command: celery -A make_celery worker --loglevel=INFO
    volumes:
      - database:/app/database
      - uploads:/app/uploads
  celery-beat:
    depends_on:
      - redis
    container_name: racine-celery-beat
    image: ghcr.io/hgrf/racine
    command: celery -A make_celery beat --loglevel=INFO
volumes:
  data:
  database:
  uploads:
