# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: "docs/mkdocs.yml"
  fail_on_warning: false

# Build all formats
formats: all

python:
   install:
   - requirements: requirements.txt
   - requirements: requirements-dev.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - make doc
