version: "3.9"
services:
  web:
    image: ghcr.io/hgrf/racine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - uploads:/app/uploads
      - database:/app/database
      - ./ssl:/etc/nginx/ssl
volumes:
  uploads:
  database:
