# based on https://stackoverflow.com/a/64373702

name: Docker deploy

on:
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - uses: ./.github/workflows/docker-build.yml@build

    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Push to DockerHub
      run: docker push holgergraef/msm

    - name: Login to ghcr
      run: echo ${{ github.token }} | docker login ghcr.io -u HolgerGraef --password-stdin

    - name: Tag image for ghcr
      run: docker tag holgergraef/msm:latest ghcr.io/holgergraef/msm:latest

    - name: Push to ghcr
      run: docker push ghcr.io/holgergraef/msm:latest
